### PR TITLE
Updated to .net standard, updated cake

### PR DESCRIPTION
**Pull request by Roemer**

### CODE REVIEW

**Comment by pitermarx** [comment]
at first glance seems ok but it's not compiling on appveyor

**Comment by pitermarx** [comment]
Executing: "C:/Program Files/dotnet/dotnet.exe" restore "src/Cake.JMeter.sln"
C:\Program Files\dotnet\sdk\2.1.403\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets(137,5): error NETSDK1045: The current .NET SDK does not support targeting .NET Core 2.2.  Either target .NET Core 2.1 or lower, or use a version of the .NET SDK that supports .NET Core 2.2. [C:\projects\cake-jmeter\src\Cake.JMeter.Tests\Cake.JMeter.Tests.csproj]

**Comment by Roemer** [comment]
Seems like the appveyor image does not support .NET Core 2.2 (yet), I lowered it to 2.1 as it anyway is only for the test project.

**Comment by pitermarx** [comment]
LGTM

**Pull request merged**
