### PR TITLE
Added possibility to interact with the plugin manager

### PR DESCRIPTION
**Pull request by Roemer**
As I have added a NuGet Package for JMeter 5.0 (https://www.nuget.org/packages/JMeter/) where I also included the Plugin-Manager and the command line for the Plugin-Manager, I now added two methods (one to directly install a plugin and another one to just run any command on the plugin manager).

### CODE REVIEW

**Comment by pitermarx** [comment]
LGTM

**Comment by pitermarx** [comment]
Could you add something to the readme indicating this new alias?

**Comment by Roemer** [comment]
Added some more methods and a small hint in the readme.

**Comment by Roemer** [comment]
Did you also check the latest commit which now makes all paths absolute (and quotes them)? I think this should make using it more simple and stable.

**Comment by pitermarx** [comment]
yup, thks

**Comment by Roemer** [comment]
Oh tests fail, I'll fix that immediately

**Comment by pitermarx** [comment]
That's strange. The AppVeyor check should have failed...

**Comment by Roemer** [comment]
Strange it is but it makes sure that they fail (as the paths are now absolute and quoted)

**Comment by Roemer** [comment]
I think the issue is that the opencover result is returned (which is exitcode 0) and the test "exit code" (which is non-zero on failed tests) which is actually inside opencover is ignored.

**Comment by Roemer** [comment]
You can fix this by using `ReturnTargetCodeOffset = 0` in the OpenCoverSettings

**Comment by Roemer** [comment]
Then it will return the exitcode of the process that is run by opencover. I'll add this as well

**Comment by Roemer** [comment]
Done in the FixTests PR

**Comment by pitermarx** [comment]
If you'd be so kind to fix the tests and add this I would appreciate it

**Comment by Roemer** [comment]
Already done :) Waiting for a new release now ;) I'll update the readme with more samples later.

**Pull request merged**
